runtime: java11
instance_class: F4
service: default
inbound_services:
  - warmup

automatic_scaling:
  max_instances: 1
  min_instances: 1
#automatic_scaling:
#  target_cpu_utilization: 0.65
#  min_instances: 2
#  max_instances: 3
#  min_pending_latency: 30ms
#  max_pending_latency: automatic
#  max_concurrent_requests: 50

#resources:
 # cpu: 1
  #memory_gb: 2.3

#handlers:
#  - url: /.*
#    secure: always
#    redirect_http_response_code: 301
#    script: auto