info:
  app:
    name: swissHealthcarePharmaceutical
    version: '0.1'
    grailsVersion: 6.1.0

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:swiss-healthcare-pharmaceutical
      driverClassName: org.h2.Driver
      username: user0024
      password: 't%lLop21'
      pooled: true
      jmxExport: true
  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:swiss-healthcare-pharmaceutical
      driverClassName: com.mysql.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      username: oberyn
      password: 'martell'
      pooled: true
      jmxExport: true
  production:
    dataSource:
      dbCreate: validate
      url: jdbc:mysql://34.121.109.172/swiss-healthcare-database
      driverClassName: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      username: root
      password: 'fQ0vinq=vyqD[|K5'
      properties:
        jmxEnabled: true
        initialSize: 5

grails:
  cors:
    enabled: true
  gorm:
    reactor:
      events: false
  views:
    default:
      codec: html
    json:
      generator:
        dateFormat: "yyyy-MM-dd HH:mm:ss"
        timeZone: "America/Mexico_City"
        locale: es_MX
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      json:
      - application/json
      - text/json
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false